import React, { useState, useEffect, useRef } from 'react';
import { FileText, Download, Eye, FileCheck } from 'lucide-react';
import ToolPreviewLayout from '../components/ui/ToolPreviewLayout';
import { renderAsync } from 'docx-preview';
import mammoth from 'mammoth';
import { safeHtml2Canvas, sanitizeCssColors } from '../utils/canvasUtils';
import { jsPDF } from 'jspdf';

export default function WordToPdf() {
  const [file, setFile] = useState(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);
  const [pageImages, setPageImages] = useState([]);
  const [pdfDataUrl, setPdfDataUrl] = useState(null);
  const [successData, setSuccessData] = useState(null);
  const [previewTab, setPreviewTab] = useState('doc');

  const docxContainerRef = useRef(null);

  useEffect(() => {
    if (window.__sharedFile) {
      if (window.__sharedFile.name.endsWith('.doc') || window.__sharedFile.name.endsWith('.docx') || window.__sharedFile.type.includes('word')) {
        handleFile(window.__sharedFile);
      }
      window.__sharedFile = null;
    }
  }, []);

  const handleFile = async (newFile) => {
    if (!newFile || (!newFile.name.endsWith('.doc') && !newFile.name.endsWith('.docx') && !newFile.type.includes('word'))) {
      alert("Please upload a valid Word document (.doc or .docx).");
      return;
    }

    setFile(newFile);
    setSuccessData(null);
    setPageImages([]);
    setPdfDataUrl(null);
    setIsLoadingPreview(true);
    setPreviewTab('doc');

    setTimeout(async () => {
      if (!docxContainerRef.current) {
        setIsLoadingPreview(false);
        return;
      }

      const container = docxContainerRef.current;
      container.innerHTML = '';

      try {
        const arrayBuffer = await newFile.arrayBuffer();
        let usedDocxPreview = false;

        // 1. Render DOCX using docx-preview directly into docxContainerRef DOM
        try {
          await renderAsync(arrayBuffer, container, undefined, {
            inWrapper: true,
            ignoreWidth: false,
            ignoreHeight: false,
            ignoreFonts: false,
            breakPages: true,
            ignoreLastRenderedPageBreak: false,
            experimental: true,
            trimXmlDeclaration: true,
            useBase64URL: true,
            useImgElement: true,
            renderHeaders: true,
            renderFooters: true,
            renderFootnotes: true,
            renderEndnotes: true,
            debug: false,
          });
          usedDocxPreview = true;
        } catch (docxErr) {
          console.warn("docx-preview parsing notice, attempting mammoth fallback:", docxErr);
        }

        // 2. Fallback for legacy .doc files
        if (!usedDocxPreview) {
          const result = await mammoth.convertToHtml({ arrayBuffer });
          const rawHtml = result.value || '<p>No content found in document.</p>';
          container.innerHTML = `
            <div style="font-family: Arial, sans-serif; font-size: 14px; line-height: 1.6; padding: 40px; color: #111827; background: #ffffff; border-radius: 8px; width: 100%;">
              ${rawHtml}
            </div>
          `;
        }

        // 3. Query individual DOCX section pages generated by docx-preview
        let pageSections = Array.from(container.querySelectorAll('section.docx, .docx-wrapper > section'));
        if (pageSections.length === 0) {
          const docxWrapper = container.querySelector('.docx-wrapper');
          pageSections = docxWrapper ? [docxWrapper] : [container];
        }

        const pdf = new jsPDF({ orientation: 'p', unit: 'pt', format: 'a4' });
        const pdfWidth = pdf.internal.pageSize.getWidth(); // 595.28
        const pdfHeight = pdf.internal.pageSize.getHeight(); // 841.89
        const pageRatio = pdfHeight / pdfWidth; // ~1.41428

        const pageImagesList = [];

        // 4. Convert each DOCX page section cleanly to a high-resolution canvas
        for (let i = 0; i < pageSections.length; i++) {
          const sectionEl = pageSections[i];

          const canvas = await safeHtml2Canvas(sectionEl, {
            scale: 2,
            useCORS: true,
            allowTaint: true,
            backgroundColor: '#ffffff',
            onclone: (clonedDoc) => {
              // Copy docx-preview styles into clonedDoc.head
              if (docxContainerRef.current) {
                const styleTags = docxContainerRef.current.querySelectorAll('style');
                styleTags.forEach((st) => {
                  try {
                    clonedDoc.head.appendChild(st.cloneNode(true));
                  } catch (e) {}
                });
              }

              // Remove global oklab/oklch stylesheets
              const styleNodes = clonedDoc.querySelectorAll('style, link[rel="stylesheet"]');
              styleNodes.forEach((st) => {
                try {
                  if (st.innerHTML && /(oklab|oklch)/i.test(st.innerHTML)) {
                    st.remove();
                  }
                } catch (e) {}
              });

              // Clean up pseudo-element font corruptions & section margins
              const fixBullets = clonedDoc.createElement('style');
              fixBullets.innerHTML = `
                .docx-wrapper ::before, .docx-wrapper ::after {
                  font-family: Arial, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif !important;
                }
                .docx-wrapper section.docx {
                  margin: 0 !important;
                  box-shadow: none !important;
                  border: none !important;
                }
              `;
              clonedDoc.head.appendChild(fixBullets);

              sanitizeCssColors(clonedDoc);
            },
          });

          if (!canvas || canvas.width === 0 || canvas.height === 0) {
            continue;
          }

          const canvasW = canvas.width;
          const canvasH = canvas.height;
          const targetCanvasPageH = Math.round(canvasW * pageRatio);

          // If section is ~1 page height, render directly as 1 page
          if (canvasH <= targetCanvasPageH * 1.12) {
            const imgData = canvas.toDataURL('image/jpeg', 0.95);

            if (i > 0) {
              pdf.addPage([pdfWidth, pdfHeight], 'p');
            }

            pdf.addImage(imgData, 'JPEG', 0, 0, pdfWidth, pdfHeight);
            pageImagesList.push(imgData);
          } else {
            // Multi-page section: slice into exact 1:1 A4 pages
            let currentY = 0;
            let sliceIndex = 0;
            while (currentY < canvasH) {
              let sliceH = Math.min(targetCanvasPageH, canvasH - currentY);
              if (sliceH < 20 && currentY > 0) break;

              const sliceCanvas = document.createElement('canvas');
              sliceCanvas.width = canvasW;
              sliceCanvas.height = targetCanvasPageH;

              const sliceCtx = sliceCanvas.getContext('2d');
              sliceCtx.fillStyle = '#ffffff';
              sliceCtx.fillRect(0, 0, sliceCanvas.width, sliceCanvas.height);

              sliceCtx.drawImage(
                canvas,
                0, currentY, canvasW, sliceH,
                0, 0, canvasW, sliceH
              );

              const sliceImgData = sliceCanvas.toDataURL('image/jpeg', 0.95);

              if (i > 0 || sliceIndex > 0) {
                pdf.addPage([pdfWidth, pdfHeight], 'p');
              }

              pdf.addImage(sliceImgData, 'JPEG', 0, 0, pdfWidth, pdfHeight);
              pageImagesList.push(sliceImgData);

              sliceCanvas.width = 0;
              sliceCanvas.height = 0;
              currentY += targetCanvasPageH;
              sliceIndex++;
            }
          }

          canvas.width = 0;
          canvas.height = 0;
        }

        const pdfBlob = pdf.output('blob');
        const pdfUrl = URL.createObjectURL(pdfBlob);

        setPageImages(pageImagesList);
        setPdfDataUrl(pdfUrl);
      } catch (err) {
        console.error("Document conversion error:", err);
        alert(`Failed to convert Word document: ${err.message || 'Please ensure it is a valid file.'}`);
      } finally {
        setIsLoadingPreview(false);
      }
    }, 100);
  };



  const convertWordToPdf = async () => {
    if (!pdfDataUrl) return;
    setIsProcessing(true);
    
    try {
      setSuccessData({
        url: pdfDataUrl,
        filename: `${file.name.replace(/\.docx?$/i, '')}_converted.pdf`,
        title: 'Conversion Complete',
        subtitle: 'Your Word document has been successfully converted to PDF with authentic formatting.',
      });
    } catch (err) {
      console.error("Word to PDF Error:", err);
      alert(`Conversion error: ${err.message || 'Failed to process document'}`);
    } finally {
      setIsProcessing(false);
    }
  };

  const resetTool = () => {
    setFile(null);
    setSuccessData(null);
    setIsProcessing(false);
    setIsLoadingPreview(false);
    setPageImages([]);
    setPdfDataUrl(null);
    setPreviewTab('doc');
  };

  const processButton = (
    <button 
      onClick={convertWordToPdf} 
      disabled={isProcessing || !file || isLoadingPreview || pageImages.length === 0}
      className="w-full px-4 py-3 bg-blue-600 border border-transparent rounded-xl shadow-md text-base font-bold text-white hover:bg-blue-700 disabled:opacity-50 flex items-center justify-center gap-2 transition-all hover:shadow-lg hover:-translate-y-0.5 relative overflow-hidden"
    >
      {isProcessing ? 'Converting...' : <><FileText className="w-5 h-5"/> Convert to PDF</>}
    </button>
  );

  const previewNode = (
    <div className="w-full flex flex-col items-center p-2 sm:p-4 bg-slate-100/70 rounded-2xl">
      {isLoadingPreview && (
        <div className="w-full flex items-center justify-center py-8 text-blue-600 text-base font-semibold">
          <FileText className="w-6 h-6 animate-bounce mr-3" /> Converting Word document format...
        </div>
      )}

      {file && (
        <div className="w-full flex flex-col items-center">
          {!isLoadingPreview && pageImages.length > 0 && (
            <div className="flex bg-white p-1 rounded-xl shadow-xs border border-gray-200 mb-6">
              <button
                onClick={() => setPreviewTab('doc')}
                className={`flex items-center gap-2 px-4 py-2 text-xs font-bold rounded-lg transition-all ${
                  previewTab === 'doc'
                    ? 'bg-blue-600 text-white shadow-sm'
                    : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                <Eye className="w-4 h-4" /> Real Document Layout
              </button>
              <button
                onClick={() => setPreviewTab('pdf')}
                className={`flex items-center gap-2 px-4 py-2 text-xs font-bold rounded-lg transition-all ${
                  previewTab === 'pdf'
                    ? 'bg-blue-600 text-white shadow-sm'
                    : 'text-gray-600 hover:text-gray-900'
                }`}
              >
                <FileCheck className="w-4 h-4" /> Generated PDF Preview ({pageImages.length} {pageImages.length > 1 ? 'Pages' : 'Page'})
              </button>
            </div>
          )}

          {/* Tab 1: Real Word Document Layout */}
          <div className={`w-full flex flex-col items-center ${previewTab === 'doc' && !isLoadingPreview ? 'flex' : 'hidden'}`}>
            <div 
              ref={docxContainerRef} 
              className="w-full max-w-[900px] overflow-x-auto flex flex-col items-center shadow-lg rounded-xl bg-slate-200/50 p-2 sm:p-6"
            />
          </div>

          {/* Hidden reference DOM during loading to guarantee dimensions are measured properly */}
          {isLoadingPreview && (
            <div 
              ref={docxContainerRef} 
              className="w-full max-w-[900px] opacity-0 pointer-events-none overflow-x-auto flex flex-col items-center bg-slate-200/50 p-2 sm:p-6"
            />
          )}

          {/* Tab 2: Generated PDF Page-by-Page Preview */}
          {!isLoadingPreview && (
            <div className={`w-full flex flex-col items-center gap-6 ${previewTab === 'pdf' ? 'flex' : 'hidden'}`}>
              {pageImages.map((pageSrc, idx) => (
                <div 
                  key={idx} 
                  className="relative bg-white shadow-xl rounded-sm border border-gray-200 overflow-hidden max-w-[800px] w-full"
                >
                  <img 
                    src={pageSrc} 
                    alt={`PDF Page ${idx + 1}`} 
                    className="w-full h-auto block"
                  />
                  <div className="absolute bottom-3 right-3 bg-slate-900/80 text-white text-xs px-2.5 py-1 rounded-md font-mono shadow-sm">
                    Page {idx + 1} of {pageImages.length}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      )}

      {!file && (
        <div className="text-center text-gray-400 py-32 font-medium text-lg">
          Upload a Word document to preview and convert to PDF
        </div>
      )}
    </div>
  );

  return (
    <ToolPreviewLayout
      title="Word to PDF"
      description="Convert your Microsoft Word documents (.docx) into standard PDF format instantly with high fidelity."
      icon={FileText}
      accept=".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document"
      file={file}
      onFileSelect={handleFile}
      onReset={resetTool}
      isProcessing={isProcessing}
      successData={successData}
      processButton={processButton}
      customPreviewNode={previewNode}
    />
  );
}








